VFDLRNP ;DSS/FHS - SILENT NOT PERFORM PROCESSOR ; 9/24/2014 6:38am
 ;;2013.1;VENDOR - DOCUMENT STORAGE SYS;**16**; 24 Sep 2014;Build 2
 Q
EN(VFDUID,VFDTST) ;Entry point to Not Perform test on an accession
 ; VFDTST - is an array of test to be "NP"
 ; VFDTST(Pointer 60)=""
 N AGE,DFN,DOB,J,L,L1,LA7PCNT,LRAA,LRAC,LRAD,LRAN,LRCCOM,LRCDT,LRCNUM
 N LRDFN,LRDIB,LRDPF,LREND,LRIDIV,LRIDT,LRINST,LRLABKY,LRLLOC,LRORIFN
 N LRMRN,LRNATURE,LRNOW,LRODT,LRODT,LRORD,LROTA,LROWDT,LRPARAM
 N LRPRAC,LRQ,LRRB,LRSCN,LRSN,LRSS,LRTNM,LRTREA,LRTSTS,LRUID
 N LRWRD,LRX,LRXVAL,LRY,OCXDT,OCXI,OCXSEQ,ORO,PNM,SEX
 N SSN,VA,VADM,VAIN,VAPD,VFDLRX,X,Y,Z
 N VAERR
GO ;
 ;D END^LRTSTOUT
 S LRSCN="",LRLABKY=1,$P(LRPARAM,U,3)=0
 S LRUID=VFDUID,LRNOW=$$NOW^XLFDT
 S VFDLRX=$$LRAA^VFDLRX(LRUID)
 I VFDLRX<1 D END Q 0
 D PT^LRX
 D EN1
 D END
 ;D END^LRTSTOUT
 Q VFDLRX
 Q
END ;
 I $G(LRAA),$G(LRAN),$G(LRAN) L -^LRO(68,LRAA,1,LRAN,1,LRAN)
 I $G(LRDFN),$G(LRIDT) L -^LR(LRDFN,LRSS,LRIDT)
 Q
EN1 ;
 ; Entry point to NP test in the array
 ; VFDTST(Pointer# to File 60)=""
 ; D LOCK^DILF("^LRO(68,LRAA,1,LRAN,1,LRAN)")
 S LRNATURE="^^^6^SERVICE CORRECTION^99ORR"
 S LRCCOM="*NP Reason: TESTING NP"
 K LRY
 S LRTSTS=0 F  S LRTSTS=$O(VFDTST(LRTSTS)) Q:$G(LREND)!($G(LRTSTS)="")  D
 . Q:'$D(^LAB(60,LRTSTS,0))  S LRTNM=$P(^(0),U)
 . S LRY=$$CHK63^LRTSTOUT(LRTSTS,LRDFN,LRSS,LRIDT)
 . Q:$G(LRY)  D SET
 . D CLNPENDG
 . D LEDICHK
 . I $D(LROTA) D LEDISET
 Q 1
SET ; Set NP data
 D SET^LRTSTOUT
 Q
CLNPENDG ; Clean-up data
 D CLNPENDG^LRTSTOUT
 Q
LEDICHK ; Check for LEDI data
 D LEDICHK^LRTSTOUT
 Q
LEDISET ; Clean LEDI data
 D LEDISET^LRTSTOUT(.LROTA)
 Q
